version: '2'

services:
  api:
    build: ./api
    image: chartrack-api
    restart: always
    ports:
      - '8000:8000'
    env_file: ./api/.env
    depends_on:
      - mongodb
    environment:
      WAIT_HOSTS: mongodb:27017
  app:
    build: ./app
    restart: always
    ports:
      - '3000:3000'
  mongodb:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootPassXXX
    ports:
      - 27017:27017
    volumes:
      - chartrack-db-data:/data/db

volumes:
  chartrack-db-data:
