version: '2'

services:
  api:
    build: ./api
    image: chartrack-api
    restart: always
    ports:
      - '8000:8000'
    env_file: ./api/.env    
  app:
    build: ./app
    restart: always
    depends_on: 
      - api
    ports:
      - '3000:80'
