name: Build Image and Deploy to EC2

on:
  pull_request:    
  push:
    branches:
    - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build docker image
        run: docker build $BUILDPARAMS -t ${DOCKERNAME}     
      - name: Login to docker
        run: docker login -u ${INPUT_USERNAME} --password-stdin ${DOCKER_REGISTRY_TOKEN}
      - name: Push to dockerhub 
        run: docker push ${DOCKERNAME}
        env:
          DOCKER_REGISTRY_TOKEN: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

  deploy_to_aws:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to EC2
